### ISSUE TITLE
Distribute Page Requirements

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/ally-guide-app#12]
Key aspects of this page is the ability to sponsor protesting teams directly 
- [x] [Technical Requirements doc](https://docs.google.com/document/d/13AcEbeJbUQG29lSE4n1FZi82AchjipfhQU_3sMDOauA/edit?usp=sharing) 
- [x] Moqup @manishapriya94 
- [ ] UI implementation (Mahrs)
- [x] [Airtable](https://airtable.com/invite/l?inviteId=invia9O9EtlwUXwX7&inviteToken=1d6d8f43634ac2c79d1d9d8306baae1897c1a961abed0d3b4f685b9b0bb5b365) (click link to request access)
- [x] Data/Airtable configuration @ankitagrawal98 
-  Functions 
   - [] Query by name, state, cause, and filters @ankitagrawal98 
   - [ ]Sort by alphabetical, by anything else? @ankitagrawal98 
   - [ ]Banner and assets @manishapriya94 @aarchuleta

Future: 
- go granular by county?
- Issue structure for submissions

**Comment by jjjaney** [comment]
Where does the "distribute" page link off from? Is it Contribute > Distribute? 

We might want to rethink some of the naming/taxonomy.
