### ISSUE TITLE
Contribute: UX issues

### ISSUE THREAD

**Issue by jjjaney** [Ally-Guide/ally-guide-app#53]
**Testing conducted with these details in mind:**
- Target audience: tech individuals, everyday people who want to learn more about their role in being more than not racist but becoming an antiracist and understanding how intersectionality applies to them
- Used `Chrome Version 84.0.4147.89 (Official Build) (64-bit)` and `Firefox 78.0.2`

## Issues

[Contribute](https://murmuring-headland-63935.herokuapp.com/Contribute)
- [ ] When visiting the page, a message that states "Sorry, no results found" briefly displays 
![image](https://user-images.githubusercontent.com/6806032/87910011-22ce5a80-ca1e-11ea-95d7-c1a434c57e77.png)

**Comment by manishapriya94** [comment]
Fixed!
