### ISSUE TITLE
Congress API - vue.js not making the call? 

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/ally-guide-app#6]
The Problem:
Postman API call worked on the congress API. Can't figure out the Vue.js part using Vue-Resource (tried Axios) as well. Those are libraries that help you to make the api calls.

This is in src, elevate.vue

<img width="1773" alt="Screen Shot 2020-06-15 at 7 28 31 AM" src="https://user-images.githubusercontent.com/9143339/84671361-23824700-aedc-11ea-82a2-f064aca7b898.png">
<img width="1754" alt="Screen Shot 2020-06-15 at 7 27 34 AM" src="https://user-images.githubusercontent.com/9143339/84671373-267d3780-aedc-11ea-9279-c39b5d4829f3.png">

**Comment by teakopp** [comment]
Taking a look 👀
