### ISSUE TITLE
⚙️Bug: Fontawesome package failing Heroku build

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/ally-guide-app#66]
**Describe the bug**
# Fortawesome is causing build to fail for the icons for Communicate page in Heroku
<img width="752" alt="Screen Shot 2020-07-22 at 6 26 25 PM" src="https://user-images.githubusercontent.com/9143339/88244503-e599e080-cc48-11ea-8fab-1108af192a1f.png">

# Steps to reproduce the behavior:
1. Go to master and install the fortawesome package after cd ally-guide
<img width="705" alt="Screen Shot 2020-07-22 at 6 22 26 PM" src="https://user-images.githubusercontent.com/9143339/88244322-51c81480-cc48-11ea-838a-c3f62b17cc16.png">

2. To verify we check in package.json for dependencies
<img width="560" alt="Screen Shot 2020-07-22 at 6 18 57 PM" src="https://user-images.githubusercontent.com/9143339/88244375-84720d00-cc48-11ea-918b-970030611402.png">

3. And make sure its routed from main.js to elevate
<img width="588" alt="Screen Shot 2020-07-22 at 6 19 05 PM" src="https://user-images.githubusercontent.com/9143339/88244365-791ee180-cc48-11ea-86f3-6fef94fca47d.png">

# See error
**Expected behavior**
After installing fontawesome as per these instructions, the icon should be usable without causnig a build failure 
**Screenshots**
<img width="917" alt="Screen Shot 2020-07-22 at 6 17 04 PM" src="https://user-images.githubusercontent.com/9143339/88244155-c484c000-cc47-11ea-9536-5e81a082942c.png">

# Possible similar issue: 
This might be a resource for solving[ fontawesome's issues with Heroku ](https://github.com/FortAwesome/Font-Awesome/issues/13296)at least for the free version, confused around instructions for deleting lock files. Any help or suggestions appreciated!

**Comment by teakopp** [comment]
Hi @manishapriya94 

Going to take a look today! My apologies it's taken me so long 😄
