### ISSUE TITLE
Communicate: Rep Menu + Twitter Action

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/ally-guide-app#75]
<img width="491" alt="Screen Shot 2020-07-27 at 2 58 21 AM" src="https://user-images.githubusercontent.com/9143339/88529595-106f9600-cfb5-11ea-9d1a-5d2b5a3a76bf.png">

- [ ] add instructions on page @manishapriya94 @mahrsbar can you make sure the div where this image will be dropped into will fit the object for mobile?
<img width="474" alt="Screen Shot 2020-07-27 at 3 06 06 AM" src="https://user-images.githubusercontent.com/9143339/88530392-29c51200-cfb6-11ea-8274-73dde474036f.png">

- [ ] rep menu @mahrsbar 
- [ ] accordion of messages/tweets @mahrsbar 
- [ ] back button: format this to be on same page as search (not hide the div) @manishapriya94

**Comment by mahrsbar** [comment]
I have built and merged the layout for this, but it's not complete. I would like to further discuss the design. After external user testing, I have discovered having buttons for the first step (method of communication) and a dropdown for the second step(type of message) is not intuitive. I propose we have the same submission method, i.e., buttons for both steps. And we could add numbering to the text to make it more clear so it's more like a step by step process as depicted in the graphic at the top of the Amplify page.
